version: '2'
services:
  web:
    build: .
    ports:
     - "9393:9393"
    volumes:
     - .:/usr/src/app
    depends_on:
     - mongo
    environment:
     - MONGO_URI=mongodb://mongo/starter
  mongo:
    image: mongo