version: '3'
services:
  web:
    build: .
    ports:
     - "9393:80"
    depends_on:
     - mongo
    environment:
     - MONGO_URI=mongodb://mongo/PROJECT_NAME
     - NODE_ENV=production
     - SESSION_SECRET=secret
  mongo:
    image: mongo